baseURL = "https://www.hairizuan.com/"
title = "Experiment, Fail, Learn, Repeat"
theme = "blowfish"
defaultContentLanguage = "en"
languageCode = "en"
enableEmoji = true
enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
disqusShortname = "www-hairizuan-com"

[pagination]
  pagerSize = 20

[permalinks]
  posts = "/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[related]
  threshold = 40
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 80

  [[related.indices]]
    name = "series"
    weight = 70

  [[related.indices]]
    name = "date"
    weight = 10
