baseurl = "https://frosty-mahavira-65c534.netlify.com"
title = "Experiment, Fail, Learn, Repeat"
copyright = "Copyright &copy; 2017 - Author Name"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

googleAnalytics = "" #Google Analytics ID

[author]
    name = "Hairizuan Noorazman"       #Author name
    github = "hairizuanbinnoorazman"     #Github username
    linkedin = "hairizuan-noorazman"   #LinkedIn username
    facebook = "hairizuan.noorazman"   #Facebook username
    twitter = ""    #Twitter username
    instagram = ""  #Instagram username

[params]
    tagline = "Life is too exciting to just keep still!"
