pygmentsCodeFences = true
baseurl = "https://www.hairizuan.com/"
title = "Experiment, Fail, Learn, Repeat"
copyright = "Copyright &copy; 2017 - Hairizuan Noorazman"
canonifyurls = true
theme = "kiera"
disqusShortname = 'www-hairizuan-com'

paginate = 50

summaryLength = 30
enableEmoji = true

googleAnalytics = "" #Google Analytics ID

[permalinks]
    posts = "/:title/"

[author]
    name = "Hairizuan Noorazman"       #Author name
    github = "hairizuanbinnoorazman"     #Github username
    linkedin = "hairizuan-noorazman"   #LinkedIn username
    facebook = "hairizuan.noorazman"   #Facebook username
    twitter = ""    #Twitter username
    instagram = ""  #Instagram username

[params]
    tagline = "Life is too exciting to just keep still!"
